# Generated by Django 6.0.3 on 2026-04-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Author's name must be unique", max_length=100, unique=True)),
                ('bio', models.TextField(help_text="Author's biography")),
                ('email', models.EmailField(error_messages={'required': 'Please provide your email address.', 'unique': 'An account with this email already exists.'}, max_length=254, unique=True)),
                ('photo', models.ImageField(blank=True, help_text="Author's profile photo", null=True, upload_to='authors/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='o', max_length=20)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['name'],
            },
        ),
    ]
