# Generated by Django 6.0.3 on 2026-04-08 20:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Book title must be unique', max_length=255, unique=True)),
                ('brief', models.TextField(help_text='Brief description of the book')),
                ('image', models.ImageField(help_text='Book cover image', upload_to='books/covers/')),
                ('no_of_page', models.PositiveIntegerField(help_text='Number of pages in the book', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Price must be greater than 0', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.JSONField(default=dict, help_text='Author info: {name, bio, photo}')),
                ('is_bestseller', models.BooleanField(default=False, help_text='Mark as bestseller')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
            },
        ),
    ]
