# Generated by Django 6.0.3 on 2026-04-08 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Author's name must be unique", max_length=100, unique=True)),
                ('bio', models.TextField(help_text="Author's biography")),
                ('photo', models.ImageField(help_text="Author's profile photo", upload_to='authors/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text="Select the book's author", on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.author'),
        ),
    ]
