# Generated by Django 6.0.3 on 2026-04-10 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('books', '0002_author_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text="Select the book's author", on_delete=django.db.models.deletion.PROTECT, related_name='books', to='authors.author'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
